#server:
#  port: 8081
#
#spring:
#  datasource:
#    url: jdbc:postgresql://database-1.caz8omygii7v.us-east-1.rds.amazonaws.com:5432/job_portal_rds
#    username: postgres
#    password: Harsha123
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#app:
#  jwt:
#    secret: "Jx8RZ6nP0qWlG1vM4yTnU7oQ2rBfH3kE9mLsA4cV8jYdK2xP7uFqN0tG5zM1rX8y"
#    expiration-ms: 3600000  # 1 hour
#
#logging:
#  level:
#    org.springframework.security: DEBUG
#    com.jobportal.job_portal: DEBUG
